# NumPy
NumPy is a fundamental library in Python for numerical computations. It provides support for arrays, matrices, and many mathematical functions. NumPy arrays are more efficient than Python lists for numerical operations, as they allow for vectorized operations, which are faster due to the lower overhead.

## NumPy Arrays
Arrays are the core structure in NumPy. Unlike Python lists, all elements in a NumPy array must have the same data type. This makes operations on NumPy arrays much faster and more memory-efficient compared to Python lists.


In [1]:
import numpy as np

# Creating a NumPy array from a Python list
my_list = [1, 2, 3, 4, 5]
array = np.array(my_list)

print("NumPy Array:", array)


NumPy Array: [1 2 3 4 5]


## Array creation

In [2]:
arr1 = np.array([1, 2, 3, 4])
zeros_arr = np.zeros((3, 3))  # 3x3 matrix of zeros
ones_arr = np.ones((2, 2))    # 2x2 matrix of ones
full_arr = np.full((3, 3), 7) # 3x3 matrix filled with 7s

print("Full Array:", full_arr)

Full Array: [[7 7 7]
 [7 7 7]
 [7 7 7]]


## Array Attributes
Once you have a NumPy array, you can examine its shape and other properties:

In [3]:
# Shape and size
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:", arr.shape)
print("Array size:", arr.size)

Array shape: (2, 3)
Array size: 6


## Indexing and Slicing
You can access elements and subarrays using indexing and slicing. NumPy supports similar slicing syntax as Python lists, but it can be extended to multiple dimensions.

In [37]:
# 1D array slicing
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Output: [20 30 40]

# 2D array slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print(arr2d[0, 1])  # Output: 2 (row 0, column 1)

# counting from 0 ofc
# [select arrays, select items in arrays]
# [start:stop (without stop), start:stop(without stop)]
# print(arr2d[:2, 1:])  # Output: [[2, 3], [5, 6]]
# print(arr2d[:, 1:])
# print(arr2d[:, 1:])
# print(arr2d[:, 1:3])
# print(arr2d[:, 2:3])
# print(arr2d[1:3, :])
print(arr2d[1:3, :2])
print(arr2d[1:3, 0:2])

[20 30 40]
[[4 5]
 [7 8]]
[[4 5]
 [7 8]]


## Reshaping Arrays
You can change the shape of an array using the reshape method. The number of elements must remain constant.

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6])
# (num of arrays, length of array)
reshaped_arr = arr.reshape((2, 3))
# reshaped_arr = arr.reshape((3,2))
# throws err
# reshaped_arr = arr.reshape((3,3))
# reshaped_arr = arr.reshape((6,1))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


## Concatenation and Splitting
You can concatenate multiple arrays together using the concatenate method and split arrays using the split method.

In [46]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated = np.concatenate((arr1, arr2))
print("Concatenated array:", concatenated)

# Splitting an array
split_arr = np.split(concatenated, 3)
print(split_arr)


Concatenated array: [1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


## Arithmetic Operations
NumPy allows you to perform element-wise operations on arrays, such as addition, subtraction, multiplication, and division. These operations are much faster than looping through lists and applying the operations manually.

In [47]:
arr = np.array([1, 2, 3, 4])
print(arr + 10)  # Output: [11, 12, 13, 14]
print(arr * 2)   # Output: [2, 4, 6, 8]


[11 12 13 14]
[2 4 6 8]


## Universal Functions (UFuncs)
NumPy has built-in universal functions (UFuncs) that perform operations on arrays element-wise. These functions are optimized to be much faster than regular Python loops.

In [48]:
arr = np.array([1, 2, 3, 4])
print(np.sqrt(arr))  # Output: [1. 1.414 1.732 2]


[1.         1.41421356 1.73205081 2.        ]


## Broadcasting
Broadcasting is one of NumPy's powerful features, which allows operations on arrays of different shapes. NumPy automatically stretches smaller arrays along larger arrays to allow arithmetic operations without explicitly reshaping them.

In [49]:
arr = np.array([1, 2, 3])
scalar = 2
print(arr + scalar)  # Broadcasting: scalar is added to each element of the array
# Output: [3, 4, 5]


[3 4 5]


## Aggregation Functions
NumPy provides several aggregation functions like `sum`, `mean`, `min`, `max`, etc., which allow you to compute summary statistics on arrays.

In [50]:
arr = np.array([1, 2, 3, 4, 5])
print("Sum:", np.sum(arr))         # Output: 15
print("Mean:", np.mean(arr))       # Output: 3.0
print("Min:", np.min(arr))         # Output: 1
print("Max:", np.max(arr))         # Output: 5


Sum: 15
Mean: 3.0
Min: 1
Max: 5


## Advanced Indexing (Fancy Indexing)
You can use an array of indices to access multiple elements at once.

In [51]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])
print(arr[indices])  # Output: [10 30 50]


[10 30 50]


## Sorting
NumPy provides efficient methods to sort arrays.

In [52]:
arr = np.array([3, 1, 5, 2, 4])
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)


Sorted array: [1 2 3 4 5]


## Masking
Masking allows you to select or modify parts of an array based on conditions. This can be useful for filtering data or replacing certain values.

In [53]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 30
print(arr[mask])

[40 50]


## Linear Algebra
NumPy also supports various linear algebra operations like dot products, matrix multiplication, and solving systems of equations.

In [54]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


## Arange

In [55]:
D = np.arange(1, 6)
print(D)

[1 2 3 4 5]


## Standard Deviation
The standard deviation is a measure of how spread out the numbers in an array are. In NumPy, you can calculate it with `np.std`.

In [56]:
arr = np.array([10, 20, 30, 40])
std_dev = np.std(arr)
print("Standard Deviation:", std_dev)

Standard Deviation: 11.180339887498949


## Random Numbers within a Range
You can generate random numbers with np.random:

- `randint()`: Generates random integers within a specified range.
- `random()`: Generates random floating-point numbers between 0 and 1.

In [57]:
# Random integers between 1 and 100
random_integers = np.random.randint(1, 100, size=(5,))
print("Random integers:", random_integers)

# Random floats between 0 and 1
random_floats = np.random.random(5)
print("Random floats:", random_floats)

Random integers: [21 91 20  1 61]
Random floats: [0.91360825 0.39509015 0.09267946 0.60485084 0.55266425]


## Identity Matrix
An identity matrix is a square matrix with ones on the diagonal and zeros elsewhere. You can create one with `np.eye()`.

In [58]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Diagonal Matrix
A diagonal matrix is a matrix in which the entries outside the main diagonal are all zero. Use `np.diag()` to create or extract the diagonal from an array.

In [59]:
# Creating a diagonal matrix
diag_matrix = np.diag([1, 2, 3])
print(diag_matrix)

# Extracting diagonal from an array
extracted_diag = np.diag(diag_matrix)
print(extracted_diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 2 3]


## 3D Arrays (Three-Dimensional Arrays)
NumPy supports arrays with any number of dimensions, including 3D arrays (or higher).

In [60]:
# Creating a 3D array
arr_3d = np.random.randint(1, 100, size=(3, 3, 3))
print(arr_3d)


[[[50 69 13]
  [51 40 13]
  [40 44 74]]

 [[31 62 42]
  [30 89  5]
  [94 53 58]]

 [[93 21 66]
  [38 80 74]
  [95 57 75]]]


## Data Type (dtype)
You can explicitly define the data type of elements in an array using the `dtype` argument, or check the data type of an existing array.

In [61]:
arr = np.array([1, 2, 3], dtype='float64')
print(arr.dtype)

float64


## Array Size, `itemsize`, and `nbytes`
- itemsize: Returns the size (in bytes) of each element in the array.
- nbytes: Returns the total memory consumed by the array.

In [62]:
arr = np.array([1, 2, 3], dtype='int32')
print("Array size:", arr.size)
print("Item size (in bytes):", arr.itemsize)
print("Total memory (nbytes):", arr.nbytes)


Array size: 3
Item size (in bytes): 4
Total memory (nbytes): 12


## Slicing Arrays
In NumPy, slicing an array returns a **view**, not a copy. This means that modifying the slice modifies the original array. If you need a copy, you can explicitly create one.

In [70]:
# Original array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing the second column (all rows)
column_slice = arr[:, 1]
print("Sliced column:", column_slice)

# Modifying the slice
column_slice[0] = 99
print("Modified array:\n", arr)  # Notice how the original array is affected

# To make a copy
column_copy = arr[:, 1].copy()
column_copy[0] = 100
print("Original array after modifying the copy:\n", arr)


Sliced column: [2 5 8]
Modified array:
 [[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]
Original array after modifying the copy:
 [[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]


## Splitting Arrays (Inverse of Concatenation)
You can split arrays into multiple sub-arrays using `np.split()`.

In [71]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arrays = np.split(arr, 3)
print(split_arrays)  # Splits into 3 arrays

[array([1, 2]), array([3, 4]), array([5, 6])]


## Broadcasting (Adding Arrays of Different Dimensions)
You can add arrays of different dimensions thanks to NumPy's broadcasting feature. The smaller array is "stretched" to fit the larger one.

In [73]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[0], [1], [2], [3]])

# Broadcasting: Adds arr1 to each row of arr2
result = arr1 + arr2
print(result)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


## Fancy Indexing (2D)
Fancy indexing can also be applied to two-dimensional arrays.

In [74]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

# Fancy indexing to select specific elements
print(arr[[0, 1], [1, 0]])  # Output: [2, 3]

[2 3]


## Histograms
You can easily generate histograms using `np.histogram()`.

In [76]:
data = np.random.randn(1000)
hist, bins = np.histogram(data, bins=10)
print(hist)
print(bins) 


[  4  27  89 208 275 242 111  34   8   2]
[-3.32424299 -2.61794558 -1.91164818 -1.20535078 -0.49905338  0.20724402
  0.91354142  1.61983883  2.32613623  3.03243363  3.73873103]


## Sorting Multi-Dimensional Arrays
You can sort arrays along any axis using `np.sort()`.

In [79]:
arr = np.array([[3, 2, 1], [6, 5, 4]])
sorted_arr = np.sort(arr, axis=1)
print(sorted_arr)


[[1 2 3]
 [4 5 6]]


## Distance Between Points
To compute the Euclidean distance between two points in space, use `np.linalg.norm`.

In [80]:
point1 = np.array([1, 2, 3])
point2 = np.array([4, 5, 6])

distance = np.linalg.norm(point1 - point2)
print("Euclidean distance:", distance)


Euclidean distance: 5.196152422706632


## Solving Systems of Linear Equations
You can solve systems of linear equations using `np.linalg.solve()`.

In [84]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

# Solve the system of equations Ax = b
x = np.linalg.solve(A, b)
print("Solution to the system:", x)


# Another example
# 2x1 + 2x2 = 1
# 3x1 + x2 = 2
X = np.array([[2, 2], [3, 1]])
Y = np.array([1, 2])
print("Solution to the system:", np.linalg.solve(X, Y))

Solution to the system: [2. 3.]
Solution to the system: [ 0.75 -0.25]


## Eigenvectors and Eigenvalues
To compute the eigenvalues and eigenvectors of a matrix, use `np.linalg.eig()`.

In [85]:
A = np.array([[3, 1], [1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [3.61803399 1.38196601]
Eigenvectors:
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
